# Generated by Django 5.2.17 on 2026-09-09 03:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rendimiento', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_base', models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, max_digits=14)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='catalogo.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_receta', to='catalogo.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='catalogo.unidadmedida')),
            ],
            options={
                'verbose_name': 'insumo de producto',
                'verbose_name_plural': 'insumos de producto',
                'ordering': ['insumo__nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'insumo'), name='unique_insumo_por_producto')],
            },
        ),
    ]
